### ISSUE TITLE
[fork] Introducing forked `@google/clasp`

### ISSUE THREAD

**Issue by PopGoesTheWza** [PopGoesTheWza/clasp#24]
# Forked `@google/clasp`

Following discussion with @khalilchoudhry on https://github.com/google/clasp/issues/12 from official `@google/clasp` repository, I started [this forked branch](https://github.com/PopGoesTheWza/clasp/tree/forked).

## Changes

It currently includes pending PRs

PR | Scope | Content
--- | --- | ---
https://github.com/google/clasp/pull/688 | enhancement | Support for environment varaible and CLI options to specify configuration files (potentially solves issues https://github.com/google/clasp/issues/12, https://github.com/google/clasp/issues/42, https://github.com/google/clasp/issues/483 and https://github.com/google/clasp/issues/524)
https://github.com/google/clasp/pull/721 | bug fix | Enhanced Windows support which attempts to solve https://github.com/google/clasp/issues/717
https://github.com/google/clasp/pull/702 | doc | Instruction to use local  `@google/clasp` install
https://github.com/google/clasp/pull/708 | doc | Update about scriptId of Project Settings File by @kenchan0130
https://github.com/google/clasp/pull/724 | doc | Instruction using gitpod by @takanakahiko
https://github.com/google/clasp/pull/713 | chore | Update dependencies

## Pending

The following PR has not (yet) been included. Feedback on it will motivate me to integrate it.

https://github.com/google/clasp/pull/715 | enhancement | Add `--account <account>` flag to `clasp open` by @maxmclau to solve https://github.com/google/clasp/issues/709

## Testing the fork

Download [this forked branch](https://github.com/PopGoesTheWza/clasp/tree/forked) and build with the command:

```shell
npm uninstall -g @google/clasp && npm install && npm audit fix && npm run build
````

The environment variables `clasp_config_project`, `clasp_config_ignore` and `clasp_config_auth` can the be used to reference config files.

The (temporary) command `clasp paths` can help you check how config files are resolved.

```shell
$ clasp paths
project .clasp.json true .clasp.json
ignore /Users/guillaumec/.claspignore true .claspignore
auth /Users/guillaumec/.clasprc.json true /Users/guillaumec/.clasprc.json
$ clasp paths -A ~/customAuth.json -I ./dev-conf -P ./dev-conf
project ./dev-conf false ./dev-conf
ignore ./dev-conf false ./dev-conf
auth /Users/guillaumec/customAuth.json false /Users/guillaumec/customAuth.json
```

The `clasp --help` command should now display new options to reference config files:

```shell
$ clasp --help
Usage: clasp <command> [options]

clasp - The Apps Script CLI

Options:
  -A, --auth <file>                           path to an auth file or a folder with a '.clasprc.json' file.
  -I, --ignore <file>                         path to an ignore file or a folder with a '.claspignore' file.
  -P, --project <file>                        path to a project file or to a folder with a '.clasp.json' file.
  -v, --version
  -h, --help                                  output usage information

[...]
```

A drafted doc is [here under `/doc`](https://github.com/PopGoesTheWza/clasp/blob/forked/docs/config-files.md)

**Comment by khalilchoudhry** [comment]
@PopGoesTheWza Config variables work. I have tried pushing with different files like .clasp.dev.json and others with cli and environment variables.
Can you explain a bit about -A flag. I don't know why but I removed the global clasprc.json and moved it under the local project. Then I used 'clasp login --status -A .clasprc.json' and it says 'You are not logged in' but if I run 'clasp push -A .clasprc.json', it successfully pushes the build. Are they allowed to run together or do I have to have a separate global clasprc.json too?

**Comment by PopGoesTheWza** [comment]
@khalilchoudhry Thanks for the feedback. The quick fork helped you somehow then.

I will try to take the time to make a proper PR within the official repo later.

Doing so, I will investigate how the authentication config is handled.

**Comment by khalilchoudhry** [comment]
@PopGoesTheWza hey, any update about PR on clasp official repo?

**Comment by PopGoesTheWza** [comment]
Too much on my plate at this moment. I hope for some latitude in the next month.

**Comment by khalilchoudhry** [comment]
Hi, I hope you are doing good. I needed to confirm if this has been merged into the original repo yet?

**Comment by NoSubstitute** [comment]
I think both this and [#42](https://github.com/google/clasp/issues/42) has had no change due to Covid19.
Would be nice there was some action on either, as I also use several different accounts to manage GAS projects.

**Comment by oshliaer** [comment]
- Will this project be supported in the future?
- Is there insurmountable difficulty to use it instead of @ google/clasp?

**Comment by PopGoesTheWza** [comment]
@contributorpw I will maintain this fork as well as the original repo.
Only this repo will be available as npm package. `forked-clasp` is a drop-in replacement to `@google/clasp`

```shell
npm uninstall -g @google/clasp
npm install -g forked-clasp
```
